sudo: required

language: python

services:
  - docker

cache:
  directories:
    - $HOME/docker

before_install:
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
- docker pull supergarotinho/bashtest
- docker pull koalaman/shellcheck

script:
- export COVERAGE_THRESHOLD=99
- ./build.sh

after_script:
- bash <(curl -s https://codecov.io/bash) -s ./test/coverage
- mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
